name: Build GDrive CLI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: prereq
      run: |
        go install github.com/github-release/github-release@latest

    - name: Change PAT
      env:
        MY_PAT: ${{ secrets.MY_PAT }}
      run: |
        find . -iname "download_upload"
        sed -i "s/github_pat_CHANGEME/$GH_PAT/g" download_upload

    - name: Build
      run: |
        cd $HOME
        chmod +x download_upload
        #ls -al _release/bin

